AC-129: Add a ribbon in the footer to display the version
BLSQ/accessmod-app pull request #32
Opened 2022-03-25 08:50 UTC by qgerome

2022-03-27 07:37 UTC, pvanliefland commented on Dockerfile
> +ARG NEXT_PUBLIC_RIBBON_VERSION
I suggest we make `SENTRY_RELEASE` more generic, call it `RELEASE`, and use it for both Sentry and the ribbon. What do you think @qgerome ?

2022-03-27 07:48 UTC, qgerome commented
Fine by me. It was mostly to be able to release in production without displaying the version but maybe we do not want that. I’ll change it on Monday.

Quentin Gérôme 
Let’s Build It SRL

> Le 27 mars 2022 à 09:38, Pierre Vanliefland ***@***.***> a écrit :
> 
> ﻿
> @pvanliefland commented on this pull request.
> 
> In Dockerfile:
> 
> > @@ -1,6 +1,7 @@
>  FROM node:17-alpine
>  
>  ARG NEXT_PUBLIC_GRAPHQL_ENDPOINT
> +ARG NEXT_PUBLIC_RIBBON_VERSION
> I suggest we make SENTRY_RELEASE more generic, call it RELEASE, and use it for both Sentry and the ribbon. What do you think @qgerome ?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-03-27 07:52 UTC, pvanliefland commented
@qgerome good point about production. Let"s discuss it on Monday, I have an additional idea regarding this.

2022-03-28 11:55 UTC, pvanliefland requested changes
LGTM - but if possible, rename to `RELEASE` - or at least adapt docs

2022-03-28 11:55 UTC, pvanliefland commented on README.md
> +- `SENTRY_RELEASE`: a release identifier for Sentry (such as a Git tag). It will also be displayed in the footer
Let's rename that to `RELEASE` (or at least `NEXT_PUBLIC_SENTRY_RELEASE` so that it corresponds to the current implementation).

2022-03-28 11:55 UTC, pvanliefland commented on Dockerfile
> +ENV NEXT_PUBLIC_SENTRY_RELEASE=$SENTRY_RELEASE
Would you have the time to rename that to `RELEASE`?

2022-03-28 11:55 UTC, pvanliefland commented on src/components/layouts/Layout/Footer.tsx
> +        <div className="text-xs">{process.env.NEXT_PUBLIC_SENTRY_RELEASE}</div>
-> `RELEASE`

2022-03-28 13:05 UTC, pvanliefland approved these changes
LGTM!

2022-03-28 13:05 UTC, merged